# Generated by Django 6.1.1 on 2026-10-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_language",
                    models.CharField(max_length=15, verbose_name="from"),
                ),
                (
                    "target_language",
                    models.CharField(max_length=15, verbose_name="into"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("translated", "translated"),
                            ("skipped", "skipped"),
                            ("error", "error"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cms.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supertext translation",
                "verbose_name_plural": "Supertext translations",
                "ordering": ["-created"],
                "permissions": [("translate", "Can translate pages with Supertext")],
                "default_permissions": ("view",),
            },
        ),
    ]
